# Generated by Django 5.0.1 on 2024-04-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_about', models.TextField()),
                ('web_contact', models.TextField()),
            ],
        ),
    ]
