# Generated by Django 5.0.1 on 2024-04-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_manuf', models.CharField(max_length=30)),
                ('product_issue', models.CharField(max_length=250)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=250)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('enquiry_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
