# Generated by Django 5.0.1 on 2024-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceenquiry',
            name='enquiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='enquiry_time',
            field=models.TimeField(),
        ),
    ]
