# Generated by Django 5.0.1 on 2024-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceenquiry_enquiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceenquiry',
            name='admin_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
