# Generated by Django 5.0.1 on 2024-04-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceenquiry_admin_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newprod_name', models.CharField(max_length=20)),
                ('newprod_desc', models.CharField(max_length=100)),
                ('newprod_price', models.CharField(max_length=10)),
                ('newprod_img', models.ImageField(upload_to='new')),
            ],
        ),
    ]
