# Generated by Django 5.0.1 on 2024-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_newproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedprod_name', models.CharField(max_length=20)),
                ('usedprod_desc', models.CharField(max_length=100)),
                ('usedprod_price', models.CharField(max_length=10)),
                ('usedprod_cond', models.CharField(max_length=10)),
                ('usedprod_img', models.ImageField(upload_to='new')),
            ],
        ),
    ]
