# Generated by Django 5.0.1 on 2024-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_usedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDmndLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmndlap_brand', models.CharField(max_length=20)),
                ('dmndlap_model', models.CharField(max_length=20)),
                ('dmndlap_proce', models.CharField(max_length=20)),
                ('dmndlap_ram', models.CharField(max_length=20)),
                ('dmndlap_stor', models.CharField(max_length=20)),
                ('dmndlap_budg', models.CharField(max_length=10)),
                ('admin_stat', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnDmndOth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmndoth_desc', models.CharField(max_length=150)),
                ('dmndoth_budg', models.CharField(max_length=20)),
                ('admin_stat', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnDmndPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmndpc_proc', models.CharField(max_length=20)),
                ('dmndpc_mobo', models.CharField(max_length=20)),
                ('dmndpc_ram', models.CharField(max_length=20)),
                ('dmndpc_stor', models.CharField(max_length=20)),
                ('dmndpc_gfx', models.CharField(blank=True, max_length=20, null=True)),
                ('dmndpc_cab', models.CharField(max_length=20)),
                ('dmndpc_psu', models.CharField(max_length=20)),
                ('dmndpc_budg', models.CharField(max_length=10)),
                ('admin_stat', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
