# Generated by Django 5.0.1 on 2024-04-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_ondmndlap_ondmndoth_ondmndpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='newprod_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usedproducts',
            name='usedprod_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usedproducts',
            name='usedprod_img',
            field=models.ImageField(upload_to='old'),
        ),
    ]
