# Generated by Django 5.0.1 on 2024-04-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_newproducts_newprod_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='newprod_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usedproducts',
            name='usedprod_name',
            field=models.CharField(max_length=100),
        ),
    ]
