# Generated by Django 5.0.1 on 2024-04-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_newproducts_newprod_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedproducts',
            name='usedprod_desc',
        ),
    ]
