# Generated by Django 5.0.1 on 2024-04-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_usedproducts_usedprod_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedproducts',
            name='usedprod_cond',
            field=models.CharField(max_length=20),
        ),
    ]
