# Generated by Django 5.0.1 on 2024-04-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_usedproducts_usedprod_cond'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondmndoth',
            name='dmndoth_prod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
