# Generated by Django 5.0.1 on 2024-05-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_ondmndlap_user_ondmndoth_user_ondmndpc_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='user',
        ),
    ]
