# Generated by Django 5.0.1 on 2024-05-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_serviceenquiry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ondmndlap',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ondmndoth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ondmndpc',
            name='user',
        ),
    ]
