# Generated by Django 5.0.1 on 2024-05-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_newproducts_user_usedproducts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedproducts',
            name='user',
        ),
    ]
