# Generated by Django 5.0.1 on 2024-05-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_usedproducts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='user',
        ),
    ]
